[package]
name = "flutterbug"
version = "0.1.0"
authors = ["not_a_seagull <jtnunley01@gmail.com>"]
description = "Safe X11 bindings for Rust"
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/not-a-seagull/flutterbug"

[dependencies]
bitflags = "1.2"
euclid = "0.20"
libc = "0.2"
thiserror = "1"
x11 = { version = "2", features = ["xlib"] }

[dev-dependencies]
anyhow = "1"
font-kit = "0.7"
pathfinder_geometry = "0.5"
